FROM python:3.11-slim
 
WORKDIR /app

# Install dependencies first (cached layer)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Declare build args
ARG JENKINS_ID
ARG JENKINS_HOST
ARG JENKINS_JOBS
ARG GEMINI_MODEL
ARG SLACK_CHANNEL

# Set environment variables for Jenkins and Geminie API key
ENV JENKINS_USER=$JENKINS_ID
ENV JENKINS_URL=$JENKINS_HOST
ENV JENKINS_JOBS=$JENKINS_JOBS
ENV GEMINI_MODEL=$GEMINI_MODEL
ENV SLACK_CHANNEL=$SLACK_CHANNEL

# Copy source
COPY agent.py .
#COPY .env .
# Create volume mount point for persistence
RUN mkdir -p /app/data
 
EXPOSE 8000
 
CMD ["python", "agent.py"]